### ISSUE TITLE
Why a Procfile

### ISSUE THREAD

**Issue by mk-pmb** [heroku/node-js-getting-started#146]
Hi, thanks for this example!

What I don't understand: Heroku should be able to guess this is a node.js project, by the `package.json` and also the `"image": "heroku/nodejs"` in `app.json`. So why does it still need a `Procfile`? Can't it just default to `web: npm start` if there is none?

Especially for projects that target many platforms, the less special-snowflake files you need, the cleaner your repo can be. If we'd further manage to guess lots of the info in `app.json` from `package.json` (e.g. select an appropriate heroku image based on the `engines` section), heroku could run many node.js projects directly, without needing any extra effort for the maintainers or the heroku user.

**Comment by jmorrell** [comment]
> What I don't understand: Heroku should be able to guess this is a node.js project, by the package.json and also the "image": "heroku/nodejs" in app.json. So why does it still need a Procfile? Can't it just default to web: npm start if there is none?

This is exactly how it works. Please see: https://devcenter.heroku.com/articles/nodejs-support#default-web-process-type

> If no `Procfile` is present in the root directory of your app during the build process, your web process will be started by running `npm start`, a script you can specify in `package.json`, eg:

```
"scripts": {
  "start": "node server.js"
}
```

An `app.json` may be required for some Pipelines feature configurations, but in general a Node app should run with no modifications.

**Comment by mk-pmb** [comment]
Thanks! So does it mean the `Procfile` in this repo is useless? If so, why keep it?

**Comment by jmorrell** [comment]
@mk-pmb I can think of at least one reason to use a `Procfile` over `npm start`

https://devcenter.heroku.com/articles/dynos#graceful-shutdown-with-sigterm

When you start a process with `npm start`, `npm` will receive the `SIGTERM` and immediately terminate the subprocess which can lead to dropped requests

**Comment by mk-pmb** [comment]
Thanks! It seems npm still can't forward signals to the app. That would make a great argument for using a custom default of `node server.js` instead of `npm start` in cases where `package.json` does not explicitly define a `start` script.

I'd like to make a PR that explains it, but while Stackoverflow says I can have comments in a Procfile with `#`, I can't find that verified in https://devcenter.heroku.com/articles/procfile . Is it an official feature? Where is it documented?

**Comment by jmorrell** [comment]
> That would make a great argument for using a custom default of node server.js instead of npm start in cases where package.json does not explicitly define a start script.

That's definitely a "yes, but".

- That convention was set by the community
- Many apps use much more complicated `start` scripts
- Thousands and thousands of apps rely on that functionality today, making it difficult to change

> I'd like to make a PR that explains it, but while Stackoverflow says I can have comments in a Procfile with #

That's a nice idea, but not something I'd want to overwhelm the average user with when they're trying to get started.

As well, I'm planning on re-working this whole example to do something with a `build` step in the near future, and I will take your feedback here into account.

**Comment by mk-pmb** [comment]
> not something I'd want to overwhelm the average user with when they're trying to get started.

If the goal is to reduce complexity, I'd make this tutorial about an app that is crash-only, and introduce a Procfile only in a later tutorial that discusses the concept of graceful shutdown, how Heroku does it, how npm undermines this, and shows a possible work-around.
