### ISSUE TITLE
WebRTC "start": "cd src&&node app.js" giving "Application Error" for my deployed app 

### ISSUE THREAD

**Issue by Miltonbhowmick** [heroku/node-js-getting-started#258]
How can i run my project? Its always giving me **Application Error** whenever i run.

My scripts:
```
 "scripts": {
"start": "cd src&&node app.js"
  },
```

**Comment by Kevn10** [comment]
"scripts": {
"start": "cd src&&node app.js"
  }; 
I think is this....
