### ISSUE TITLE
Connect an Authenticator App

### ISSUE THREAD

**Issue by jamessv** [heroku/node-js-getting-started#308]
While Signup on Windows

Connect an authenticator app that generates verification codes. You can use the codes when we need to verify your identity.

Download and install an authenticator app on your mobile device.
Use the app to scan this QR code.
Enter the code generated by the app.

Verification Code:  ******  That code is invalid or expired. Try another.

Using google Authenticator App

**Comment by colincasey** [comment]
Hi @jamessv, can you provide more context here? I'm not sure if this is a suggestion or a complaint.

**Comment by jamessv** [comment]
> Hi @jamessv, can you provide more context here? I'm not sure if this is a suggestion or a complaint.

@colincasey Its a complaint
