### ISSUE TITLE
Deploy to Heroku button in README.md on GitHub does not work

### ISSUE THREAD

**Issue by keitaito** [heroku/node-js-getting-started#61]
Hi!

I was checking how Deploy to Heroku button works on [Heroku Dev Center](https://devcenter.heroku.com/articles/heroku-button). This repo node-js-getting-started is used as example for Deploy to Heroku button in the page, and it works there. "Create New App" page is displayed when I click the button.

However, when I click the Deploy to Heroku button in README.md in this repo on GitHub, "Create New App" page is not displayed, and an error page is displayed on Heroku. The error says "No app.json located in the repo URL provided. Make sure that an app.json file exists in the project root directory." I attached a screen shot here.

Do you know why the button doesn't work in README.md page? It seems the button is implemented [as implicit template](https://devcenter.heroku.com/articles/heroku-button#using-an-implicit-template), and it should work in markdown file as well as html. 

Thanks!

![screen shot 2016-12-31 at 9 49 53 pm](https://cloud.githubusercontent.com/assets/3249850/21580418/9a5ea13c-cfa8-11e6-8547-8f02f2ff5ff6.png)

**Comment by jonmountjoy** [comment]
Yes, I could make it an explicit parameter.  However, then anyone who forks the repo, will have to change the button or else it will just deploy my version.

**Comment by piperchester** [comment]
I think this issue is now obsolete? The button seems to work for me on latest Canary (v61).

**Comment by davidchengIC** [comment]
Today I ran into this exact issue.  Should I open a new issue, or will this one be re-opened?

**Comment by jonmountjoy** [comment]
I can't reproduce this @davidchengIC Can you tell me the exact steps you followed?  Where you on this URL when you pushed the button?  https://github.com/heroku/node-js-getting-started/

**Comment by davidchengIC** [comment]
It's working now, I'm not sure what happened.  I was on the URL of my own repo for a Salesforce Trailhead module but I can't remember which one.

**Comment by Christyjoseph1** [comment]
Same problem for me so how to remove and create a application

**Comment by gidiem** [comment]
Same issue - had to add the explicit template. Not sure what the issue is but I guess this is a workaround.

**Comment by ProThinkersGang** [comment]
i had an app.json file in my repository but still it shows an error while creating an app. "No app.json located in the repo URL provided. Make sure that an app.json file exists in the project root directory." How to resolve it

**Comment by mHaulkhory** [comment]
The HTML code for the deploy button

<a href="https://heroku.com/deploy?template=https://github.com/YOUR_USERNAME/intro-to-heroku">
  <img src="https://www.herokucdn.com/deploy/button.svg" alt="Deploy">
</a>
