### ISSUE TITLE
Can't get this to do a simple hello world

### ISSUE THREAD

**Issue by patientplatypus** [heroku/node-js-getting-started#75]
If I make a simple hello world call on the backend in routes/index.js and try and call it from the front it doesn't work.

```
router.post('/hello', function(req, res, next) {
  console.log('successontheback')
  res.send('hello there sailor');
});
```
My call from the front end

```
 axios.post('http://localhost:5000/hello')
         .then((response)=>{
          console.log('response from the hello call ', response);
         })
        .catch(()=>{
          console.log('hello axios error');
        });
```

And the error

```
Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:80999 hello axios error
```

So. Whatever configurations you have here are simply not working out of the box and I do not know how to fix them.

If I try and push my own working node.js file to heroku that works on my localhost then I get "application error" (if I push this it works, but of course there's no way that I can route to it for backend calls). Really have no idea how to get your service to work. Incredibly disappointed.

**Comment by jmorrell** [comment]
Hey @patientplatypus 

Sounds like you might have a couple of things set up slightly off. Want to open a support ticket at help.heroku.com so we can help you?

Note that this call `axios.post('http://localhost:5000/hello')` will only send a query to your local machine and not to Heroku.
