### ISSUE TITLE
heroku local web error

### ISSUE THREAD

**Issue by CharlBest** [heroku/node-js-getting-started#81]
Hi.
I was following the Getting Started on Heroku with Node.js tutorial and then when I ran "heroku local web" it gave me this error:

![image](https://user-images.githubusercontent.com/6147400/30916661-3abfb308-a39a-11e7-9bf4-343285671694.png)

I then removed the debug flag in the Procfile and it worked. 

![image](https://user-images.githubusercontent.com/6147400/30916759-79f4248c-a39a-11e7-8c9c-3ea411131ec6.png)

The documentation also shows the Procfile without the debug file.

![image](https://user-images.githubusercontent.com/6147400/30916835-a112b77c-a39a-11e7-9c6f-c31311c4c5ba.png)

Not sure if its a bug or not or maybe node version mismatch but thought I'd let you guys know. 

First time using Heroku. Really liking it!

Update: I see it was added 20 days ago in commit https://github.com/heroku/node-js-getting-started/commit/182236754e00f6690ad710fc1ea52fd479e67abd#diff-5bd6b85c2d6fc987875f4bf82de2a15a

**Comment by skyrol** [comment]
I encountered the same problem in testing this. Another way to fix it is by installing node --inspect, like this npm install --save --save-exact node --inspect . After that, in your Procfile, you can replace --debug with --inspect and it should work.

**Comment by akhilbh92** [comment]
Thanks @skyrol ... Your solution worked for me.
