### ISSUE TITLE
[Upgrade Issues] Heroku: Update Node to latest version

### ISSUE THREAD

**Issue by IamManchanda** [heroku/node-js-getting-started#85]
I don't know whether this is right repo but...

https://stackoverflow.com/questions/46728176/heroku-update-node-to-latest-version

**Comment by IamManchanda** [comment]
cc @jmorrell

**Comment by jmorrell** [comment]
I'm afraid this is an issue with configuring your local machine @IamManchanda, and not related to Heroku
