### ISSUE TITLE
Update Getting Started Documentation

### ISSUE THREAD

**Issue by BWillis98** [heroku/node-js-getting-started#94]
Since the commit: 787a0397af4e2a295607cced85aa882931c18d3d the guide on your website no longer lines up with the code. Here's an example of one of the steps that doesn't line up with the code base anymore: https://devcenter.heroku.com/articles/getting-started-with-nodejs#push-local-changes. It's pretty obvious how to make it work, but I still think the getting-started guide on heroku's site should match the repository.

**Comment by gnass** [comment]
My understanding as to what the updated index.js example should be as follows:

`const cool = require('cool-ascii-faces')
const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('pages/index'))
  .get('/cool', (req, res) => res.send(cool()))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))`

**Comment by jmorrell** [comment]
The guide now matches the repository :)
